name: Node.js CI and Codecov
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["14", "16", "18"]
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install project dependencies
        run: npm ci
      - name: Run tests using ava
        run: npx nyc --reporter=lcov ava
      - name: Check code style and formatting with rome
        run: npx rome ci .eleventy lib/
      - name: Upload coverage to Codecov.io
        uses: codecov/codecov-action@v3
      
